version: '2.4'
services:
  nvme_exporter:
    container_name: "nvme_exporter"
    image: "ghcr.io/nebula-it/nvme_exporter:latest"
    restart: unless-stopped
    privileged: true
    expose:
      - "9998"
